# Generated by Django 4.0.6 on 2022-07-10 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_connaissance', models.CharField(max_length=128)),
                ('forme_connaissance', models.CharField(choices=[('tableau', 'tableau'), ('pdf', 'pdf'), ('image', 'image')], max_length=10)),
                ('date_creation', models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime.now)),
                ('status_vue', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
