# Generated by Django 4.0.6 on 2022-07-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connaissance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connaissance',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
