# Generated by Django 4.0.6 on 2022-07-11 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connaissance', '0002_alter_connaissance_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connaissance',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
