# Generated by Django 4.0.6 on 2022-09-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connaissance', '0004_alter_connaissance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='connaissance',
            name='url_connaissance',
            field=models.CharField(default=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='connaissance',
            name='forme_connaissance',
            field=models.CharField(choices=[('document', 'document'), ('pdf', 'pdf'), ('image', 'image')], max_length=10),
        ),
    ]
