# Generated by Django 4.0.6 on 2022-09-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connaissance', '0005_connaissance_url_connaissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connaissance',
            name='icon_connaissance',
            field=models.CharField(choices=[('csv', 'file-csv-solid.svg'), ('pdf', 'file-pdf-solid.svg'), ('image', 'image-solid.svg')], default=True, max_length=25),
        ),
    ]
