# Generated by Django 4.0.6 on 2022-09-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connaissance', '0006_connaissance_icon_connaissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connaissance',
            name='forme_connaissance',
            field=models.CharField(choices=[('tableau', 'tableau'), ('document', 'document'), ('image', 'image')], max_length=10),
        ),
        migrations.AlterField(
            model_name='connaissance',
            name='icon_connaissance',
            field=models.CharField(choices=[('file-csv-solid.svg', 'file-csv-solid.svg'), ('file-pdf-solid.svg', 'file-pdf-solid.svg'), ('image-solid.svg', 'image-solid.svg')], default=True, max_length=25),
        ),
    ]
