# Generated by Django 4.0.6 on 2022-07-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaire', '0002_alter_commentaire_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='created_for',
            field=models.CharField(max_length=255),
        ),
    ]
