# Generated by Django 4.0.6 on 2022-07-12 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaire', '0007_remove_commentaire_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='created_at',
            field=models.DateTimeField(blank='True', default=datetime.datetime.now),
        ),
    ]
