# Generated by Django 4.0.6 on 2022-07-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentaire', '0008_alter_commentaire_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-created_at']},
        ),
    ]
