# Generated by Django 4.0.6 on 2022-09-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaire', '0009_alter_commentaire_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='created_by',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
