# Generated by Django 4.0.6 on 2022-07-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_employer',
            new_name='is_expert',
        ),
    ]
