# Generated by Django 4.0.6 on 2022-09-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_rename_is_employer_userprofile_is_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
